/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// ai85-vit
// This file was @generated by ai8xize.py --verbose --test-dir demos --prefix ai85-vit --checkpoint-file trained/ai85-vit-patch_size_1_pos_embed_q8.pth.tar --config-file networks/ai8x-vit.yaml --device MAX78000 --overwrite --debug --softmax

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 1-channel 28x28 data input (784 bytes / 196 32-bit words):
// HWC 28x28, channels 0 to 0
static const uint32_t input_0[] = SAMPLE_INPUT_0;

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x50400000, input_0, 784);
}

// Expected output of layer 19 (head) for ai85-vit given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

// Classification layer:
static int32_t ml_data[CNN_NUM_OUTPUTS];
static q15_t ml_softmax[CNN_NUM_OUTPUTS];

void softmax_layer(void)
{
  cnn_unload((uint32_t *) ml_data);
  softmax_q17p14_q15((const q31_t *) ml_data, CNN_NUM_OUTPUTS, ml_softmax);
}

int main(void)
{
  int i;
  int digs, tens;

  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test ai85-vit ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  load_input(); // Load data input
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  if (check_output() != CNN_OK) fail();
  softmax_layer();

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate inference time: %u us\n\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral

  printf("Classification results:\n");
  for (i = 0; i < CNN_NUM_OUTPUTS; i++) {
    digs = (1000 * ml_softmax[i] + 0x4000) >> 15;
    tens = digs % 10;
    digs = digs / 10;
    printf("[%7d] -> Class %d: %d.%d%%\n", ml_data[i], i, digs, tens);
  }

  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 46,962,304 ops (46,778,624 macc; 137,024 comp; 46,656 add; 0 mul; 0 bitwise)
            True MACs: 0
    Layer 0 (patch_embed.conv.0): 501,760 ops (451,584 macc; 50,176 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1 (patch_embed.conv.1): 28,951,552 ops (28,901,376 macc; 50,176 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2 (patch_embed.conv.2): 3,037,824 ops (2,985,984 macc; 5,184 comp; 46,656 add; 0 mul; 0 bitwise)
    Layer 3 (blocks.0.norm1): 331,776 ops (331,776 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4 (blocks.0.attn): 1,343,488 ops (1,343,488 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 5 (blocks.0.norm2): 335,872 ops (335,872 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6 (blocks.0.ff.0): 1,353,984 ops (1,343,488 macc; 10,496 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7 (blocks.0.ff.3): 1,343,488 ops (1,343,488 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8 (blocks.1.norm1): 335,872 ops (335,872 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9 (blocks.1.attn): 1,343,488 ops (1,343,488 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 10 (blocks.1.norm2): 335,872 ops (335,872 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11 (blocks.1.ff.0): 1,353,984 ops (1,343,488 macc; 10,496 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12 (blocks.1.ff.3): 1,343,488 ops (1,343,488 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13 (blocks.2.norm1): 335,872 ops (335,872 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14 (blocks.2.attn): 1,343,488 ops (1,343,488 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 15 (blocks.2.norm2): 335,872 ops (335,872 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16 (blocks.2.ff.0): 1,353,984 ops (1,343,488 macc; 10,496 comp; 0 add; 0 mul; 0 bitwise)
    Layer 17 (blocks.2.ff.3): 1,343,488 ops (1,343,488 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18 (norm): 335,872 ops (335,872 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 19 (head): 1,280 ops (1,280 macc; 0 comp; 0 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 173,696 bytes out of 442,368 bytes total (39.3%)
  Bias memory:   1,418 bytes out of 2,048 bytes total (69.2%)
*/

